-- Exercise Data Replace: Step 1 - Create staging table
-- Run this FIRST before the data files

DROP TABLE IF EXISTS _exercise_staging;

CREATE TABLE _exercise_staging (
    id UUID PRIMARY KEY,
    name TEXT,
    category TEXT,
    equipment TEXT,
    primary_muscles TEXT[],
    secondary_muscles TEXT[],
    description TEXT,
    video_code TEXT,
    video_filename TEXT,
    gender TEXT,
    is_custom BOOLEAN,
    created_at TIMESTAMPTZ,
    steps_to_perform TEXT,
    movement_pattern TEXT,
    force_type TEXT,
    movement_type TEXT,
    laterality TEXT,
    plane_of_motion TEXT,
    difficulty_level INTEGER,
    complexity_score INTEGER,
    strength_rating INTEGER,
    hypertrophy_rating INTEGER,
    power_rating INTEGER,
    endurance_rating INTEGER,
    body_position TEXT,
    bench_angle TEXT,
    grip_type TEXT,
    grip_width TEXT,
    optimal_rep_range_min INTEGER,
    optimal_rep_range_max INTEGER,
    placement_in_workout TEXT,
    fatigability INTEGER,
    popularity_score INTEGER,
    home_gym_friendly BOOLEAN,
    instructions TEXT,
    workout_type TEXT,
    practicality_score INTEGER,
    fat_loss_rating INTEGER,
    general_fitness_rating INTEGER,
    is_compound BOOLEAN,
    supersetable BOOLEAN,
    exercise_family TEXT,
    base_exercise_name TEXT,
    complementary_families TEXT,
    is_equipment_primary BOOLEAN,
    equipment_category TEXT,
    duration_based BOOLEAN,
    recommended_sets INTEGER,
    rest_seconds INTEGER,
    muscles_worked_count INTEGER,
    priority_build_muscle INTEGER,
    priority_get_lean INTEGER,
    priority_home INTEGER,
    priority_gym INTEGER
);
