import { NextRequest, NextResponse } from 'next/server'
import { verifyAdmin } from '@/lib/verify-admin'

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || ''
const GITHUB_OWNER = process.env.GITHUB_REPO_OWNER || ''
const GITHUB_REPO = process.env.GITHUB_REPO_NAME || ''
const GITHUB_API = 'https://api.github.com'

async function githubFetch(path: string, options: RequestInit = {}) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  })
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub API ${res.status}: ${body}`)
  }
  return res.json()
}

export async function POST(req: NextRequest) {
  try {
    const adminAuth = await verifyAdmin(req)
    if (!adminAuth.valid) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    if (!GITHUB_TOKEN || !GITHUB_OWNER || !GITHUB_REPO) {
      return NextResponse.json(
        { error: 'GitHub integration not configured. Set GITHUB_TOKEN, GITHUB_REPO_OWNER, and GITHUB_REPO_NAME in .env.local' },
        { status: 500 },
      )
    }

    const { suggestion_id, title, description, file_path, code_diff, session_id } = await req.json()

    if (!file_path || !code_diff) {
      return NextResponse.json({ error: 'Missing file_path or code_diff' }, { status: 400 })
    }

    const branchName = `fix/dev-log-${(session_id || 'unknown').slice(0, 8)}-${Date.now()}`

    // 1. Get the default branch's latest commit SHA
    const repo = await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}`)
    const defaultBranch = repo.default_branch || 'main'

    const ref = await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/ref/heads/${defaultBranch}`)
    const baseSha = ref.object.sha

    // 2. Create a new branch
    await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    })

    // 3. Get the current file content
    let currentContent = ''
    let fileSha = ''
    try {
      const file = await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${file_path}?ref=${branchName}`)
      currentContent = Buffer.from(file.content, 'base64').toString('utf-8')
      fileSha = file.sha
    } catch {
      return NextResponse.json({ error: `File not found: ${file_path}` }, { status: 404 })
    }

    // 4. Apply the diff (simple line replacement for now)
    let newContent = currentContent
    const diffLines = code_diff.split('\n')
    const oldLines: string[] = []
    const newLines: string[] = []
    for (const line of diffLines) {
      if (line.startsWith('---') || line.startsWith('+++') || line.startsWith('@@')) continue
      if (line.startsWith('-')) oldLines.push(line.slice(1))
      else if (line.startsWith('+')) newLines.push(line.slice(1))
    }

    if (oldLines.length > 0) {
      const oldBlock = oldLines.join('\n')
      const newBlock = newLines.join('\n')
      if (currentContent.includes(oldBlock)) {
        newContent = currentContent.replace(oldBlock, newBlock)
      }
    }

    if (newContent === currentContent) {
      return NextResponse.json({ error: 'Could not apply diff — old code not found in file' }, { status: 400 })
    }

    // 5. Commit the change
    await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/contents/${file_path}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `fix: ${title}\n\nAuto-generated from dev session log analysis.\nSession: ${session_id || 'unknown'}`,
        content: Buffer.from(newContent).toString('base64'),
        sha: fileSha,
        branch: branchName,
      }),
    })

    // 6. Create a draft PR
    const pr = await githubFetch(`/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title: `[Dev Log Fix] ${title}`,
        body: `## Auto-Generated Fix\n\n${description}\n\n**File:** \`${file_path}\`\n**Session:** ${session_id || 'N/A'}\n**Suggestion ID:** ${suggestion_id || 'N/A'}\n\n---\n*This PR was auto-generated by Claude from a dev session log analysis. Review carefully before merging.*`,
        head: branchName,
        base: defaultBranch,
        draft: true,
      }),
    })

    return NextResponse.json({
      pr_url: pr.html_url,
      pr_number: pr.number,
      branch: branchName,
    })
  } catch (err) {
    console.error('GitHub PR error:', err)
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'PR creation failed' },
      { status: 500 },
    )
  }
}
