#!/usr/bin/env bash
# classifier_lint_make_fix_pr.sh — Phase 12 Tier 4 #4 (2026-04-25, PR-G)
#
# Drafts a single "classifier-bypass cleanup" PR by:
#   1. Running scripts/classifier_lint.py --json over Fit33/.
#   2. For each violation, inserting a `// CLASSIFIER LINT TODO:` block
#      immediately above the offending `AppLogger.error/critical` line with
#      the suggested `NetworkErrorClassifier.log(...)` wrap. The original
#      call stays in place so reviewers can A/B the diff before merging —
#      the dev replaces the AppLogger line with the wrap once they pick the
#      correct `op:` / `endpoint:` / `category:` from `PerformanceSignposts.Op`.
#   3. Creating a branch `chore/classifier-bypass-cleanup-YYYYMMDD`, committing,
#      pushing, and opening a PR via `gh`.
#
# IMPORTANT
# ---------
# - Idempotent: re-running on a clean repo with no violations is a no-op.
#   When TODO blocks are already present, the inserted block is skipped so the
#   file does not balloon.
# - Skips silently if `gh` is missing or the user is not authenticated — the
#   diff is still applied to the working tree so a human can push it.
# - The auto-injected TODO blocks are intentionally non-compiling-friendly
#   (they're comments) so the build keeps passing while a dev fills them in.
# - Suppressed violations (`// classifier_lint:allow`) are excluded by the
#   linter, so this script never reopens them.
#
# USAGE
# -----
#   bash scripts/classifier_lint_make_fix_pr.sh [--dry-run] [--no-pr]
#
# Flags:
#   --dry-run : Print what would change but make no edits / commits.
#   --no-pr   : Apply edits + commit, but skip `gh pr create`.
#
# Requires: python3, git, gh (optional — `--no-pr` works without it).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DRY_RUN=0
NO_PR=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --no-pr)   NO_PR=1 ;;
    -h|--help)
      sed -n '2,30p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

# 1. Run the lint and capture JSON to a temp file so we can pass it to python.
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
JSON_FILE="$TMP_DIR/violations.json"
python3 scripts/classifier_lint.py --json --root Fit33 > "$JSON_FILE" || true

COUNT=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('count',0))" "$JSON_FILE")

if [[ "$COUNT" == "0" ]]; then
  echo "[classifier_lint_make_fix_pr] No violations — nothing to do."
  exit 0
fi

echo "[classifier_lint_make_fix_pr] $COUNT violation(s) found."

# 2. Apply the suggested-fix block above each offending line.
#    All file mutation lives in the Python helper below — keeps us off
#    macOS bash 3.2's missing `mapfile` and gives us the unicode-safe
#    line splicing we need.
CHANGED_LIST="$TMP_DIR/changed_files.txt"

DRY_RUN_FLAG=$DRY_RUN python3 - "$JSON_FILE" "$CHANGED_LIST" <<'PY'
import json
import os
import sys
from pathlib import Path

json_path, changed_list_path = sys.argv[1], sys.argv[2]
dry_run = os.environ.get("DRY_RUN_FLAG") == "1"

with open(json_path) as fh:
    data = json.load(fh)

# Group by file, sort each group by applogger_line desc so each insert
# preserves the validity of remaining target line numbers.
by_file = {}
for v in data.get("violations", []):
    by_file.setdefault(v["file"], []).append(v)

changed_files = []

for file_rel, edits in by_file.items():
    p = Path(file_rel)
    if not p.exists():
        print(f"  ! skipping {file_rel} (not found)", file=sys.stderr)
        continue

    text = p.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=False)
    edits_sorted = sorted(edits, key=lambda e: -int(e["applogger_line"]))

    file_modified = False
    for ed in edits_sorted:
        target = int(ed["applogger_line"])
        idx = target - 1
        if idx < 0 or idx >= len(lines):
            print(f"  ! {file_rel}:{target} out of range, skipping", file=sys.stderr)
            continue

        # Idempotency guard — if the previous line already has our marker,
        # don't re-insert.
        if idx > 0 and "CLASSIFIER LINT TODO" in lines[idx - 1]:
            continue

        offender = lines[idx]
        indent = ""
        for ch in offender:
            if ch in (" ", "\t"):
                indent += ch
            else:
                break

        # Render the suggested-fix snippet as a comment block.
        suggested = ed.get("suggested_fix", "")
        sug_lines = suggested.splitlines() or [""]
        sug_block = "\n".join(f"{indent}// {ln}" for ln in sug_lines)

        block = (
            f"{indent}// CLASSIFIER LINT TODO (auto-generated by "
            f"scripts/classifier_lint_make_fix_pr.sh):\n"
            f"{indent}// QP invariant 25a — replace the AppLogger call below "
            f"with this wrap once\n"
            f"{indent}// you have picked the right op/endpoint/category. "
            f"Suppress with\n"
            f"{indent}// `// classifier_lint:allow` ONLY when the classifier "
            f"is unavailable\n"
            f"{indent}// (e.g. bootstrap before SupabaseManager.shared.isAuthenticated).\n"
            f"{indent}//   error binding: `{ed.get('error_var', 'error')}`\n"
            f"{indent}// ---- suggested replacement ----\n"
            f"{sug_block}\n"
            f"{indent}// ---- end suggested replacement ----"
        )

        lines[idx:idx] = block.splitlines()
        file_modified = True

    if not file_modified:
        continue

    new_text = "\n".join(lines)
    if text.endswith("\n") and not new_text.endswith("\n"):
        new_text += "\n"

    if dry_run:
        print(f"  (dry-run) would patch {file_rel}")
    else:
        p.write_text(new_text, encoding="utf-8")
        changed_files.append(file_rel)
        print(f"  patched {file_rel}")

with open(changed_list_path, "w") as fh:
    for f in changed_files:
        fh.write(f + "\n")
PY

if [[ "$DRY_RUN" == "1" ]]; then
  echo "[classifier_lint_make_fix_pr] dry-run complete. Run without --dry-run to apply."
  exit 0
fi

if [[ ! -s "$CHANGED_LIST" ]]; then
  echo "[classifier_lint_make_fix_pr] No files actually changed (all sites already had TODOs)."
  exit 0
fi

# 3. Commit + push + open PR.
DATE_TAG=$(date +%Y%m%d)
BRANCH="chore/classifier-bypass-cleanup-${DATE_TAG}"

git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Stage the changed files. xargs -d '\n' handles paths with spaces.
xargs -I {} git add -- "{}" < "$CHANGED_LIST"

git commit -m "$(cat <<EOF
chore(classifier): annotate AppLogger.error bypasses with NEC suggestions

Auto-generated by scripts/classifier_lint_make_fix_pr.sh.
Each violation has an inline TODO block with the recommended
NetworkErrorClassifier.log(...) wrap. Devs replace the offending
AppLogger.error / .critical line with the wrap once they pick the
right op / endpoint / category from PerformanceSignposts.Op.

See QUALITY_PERFORMANCE_AGENT.md invariant 25a / 25g.
EOF
)"

if [[ "$NO_PR" == "1" ]]; then
  echo "[classifier_lint_make_fix_pr] Branch $BRANCH committed locally. Skipping PR (--no-pr)."
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "[classifier_lint_make_fix_pr] gh not installed — branch $BRANCH committed locally. Push + open PR manually." >&2
  exit 0
fi

git push -u origin "$BRANCH"
gh pr create \
  --title "chore(classifier): annotate AppLogger.error bypasses with NetworkErrorClassifier suggestions" \
  --body "$(cat <<EOF
## Summary
Auto-drafted by \`scripts/classifier_lint_make_fix_pr.sh\` on $(date +%Y-%m-%d).

For every \`catch { ... AppLogger.error(...) ... }\` block in a Supabase-touching
file that does not already use \`NetworkErrorClassifier\`, this PR inserts a
\`// CLASSIFIER LINT TODO:\` comment block above the offending line with the
recommended \`NetworkErrorClassifier.log(...)\` wrap.

The original \`AppLogger.error\` calls are left in place so the diff is reviewable.
Each TODO marker has the inferred \`error\` binding name. The reviewer fills in:

- \`op:\` — pick from \`Fit33/PerformanceSignposts.swift::Op\`.
- \`endpoint:\` — RPC name or URL path.
- \`category:\` — \`.network\` / \`.auth\` / \`.data\` / \`.health\` / etc.

Once a TODO is converted, **delete** the TODO block + the original \`AppLogger.error\` line.

## Why
QUALITY_PERFORMANCE_AGENT invariant 25a — every Supabase-touching catch routes
through \`NetworkErrorClassifier\` so transient \`NSURLErrorTimedOut\` / cancelled /
auth-expired errors don't fingerprint as bugs. See also invariant 25g and
\`scripts/classifier_lint.py\`.

## Test plan
- [ ] CI \`classifier-lint\` passes (warn-only mode).
- [ ] At least one converted catch block builds.
- [ ] Sample build ships without surfacing transient timeouts in bug-intel.
EOF
)"
